  version: '3.8'

  services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8000:80
      depends_on:
        - db
    db:
      image: postgres
      ports:
        - "5432:5432"
      restart: always
      env_file:
        - .env
      volumes:
        - db_data:/var/lib/postgresql/data/

  volumes:
    db_data: